services:
  # --- База данных ---
  postgres:
    image: postgres:15-alpine
    container_name: diploma-postgres
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: warehouse_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U app_user -d warehouse_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Брокер сообщений ---
  redis:
    image: redis:7-alpine
    container_name: diploma-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  # --- Бэкенд (FastAPI) ---
  backend:
    build: ./backend
    container_name: diploma-backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://app_user:dev_password@postgres:5432/warehouse_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  # --- Воркер Celery (для тяжелых задач CV и упаковки) ---
  celery_worker:
    build: ./backend
    container_name: diploma-celery
    command: celery -A app.core.celery_app.celery_app worker --loglevel=info --concurrency=1
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    environment:
      - DATABASE_URL=postgresql+asyncpg://app_user:dev_password@postgres:5432/warehouse_db
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    depends_on:
      - backend
      - redis

  # --- Фронтенд (Next.js) ---
  frontend:
    build: ./frontend
    container_name: diploma-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  pgdata:
  uploads_data:
