"""some_new_change

Revision ID: 69053d637c57
Revises: add_status_final
Create Date: 2026-05-14 16:11:24.913895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69053d637c57'
down_revision: Union[str, None] = 'add_status_final'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_items_measurement', table_name='packing_items')
    op.drop_index('ix_results_selected', table_name='packing_results', postgresql_where='(selected = true)')
    op.alter_column('packing_sessions', 'status',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_index('ix_sessions_created', table_name='packing_sessions')
    op.drop_index('ix_products_qr', table_name='products', postgresql_where='(qr_code IS NOT NULL)')
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_login_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_login_key', 'users', ['login'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.create_index('ix_products_qr', 'products', ['qr_code'], unique=True, postgresql_where='(qr_code IS NOT NULL)')
    op.create_index('ix_sessions_created', 'packing_sessions', ['created_at'], unique=False)
    op.alter_column('packing_sessions', 'status',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.create_index('ix_results_selected', 'packing_results', ['session_id', 'selected'], unique=False, postgresql_where='(selected = true)')
    op.create_index('ix_items_measurement', 'packing_items', ['measurement_id'], unique=False)
    # ### end Alembic commands ###
