"""Initial schema

Revision ID: 953f31aa4b13
Revises: 
Create Date: 2026-05-01 21:41:34.139124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953f31aa4b13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('qr_code', sa.String(length=255), nullable=True),
    sa.Column('ref_length_mm', sa.Float(), nullable=True),
    sa.Column('ref_width_mm', sa.Float(), nullable=True),
    sa.Column('ref_height_mm', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('qr_code')
    )
    op.create_index('ix_products_qr', 'products', ['qr_code'], unique=True, postgresql_where='qr_code IS NOT NULL')
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("role IN ('worker', 'admin')", name='check_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_index('ix_users_login', 'users', ['login'], unique=True)
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('length_mm', sa.Float(), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('height_mm', sa.Float(), nullable=False),
    sa.Column('delta_pct', sa.Float(), nullable=True),
    sa.Column('verified_ok', sa.Boolean(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('measured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_measurements_measured_at', 'measurements', ['measured_at'], unique=False)
    op.create_index('ix_measurements_product', 'measurements', ['product_id'], unique=False)
    op.create_index('ix_measurements_user', 'measurements', ['user_id'], unique=False)
    op.create_table('packing_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'done', 'error')", name='check_session_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_created', 'packing_sessions', ['created_at'], unique=False)
    op.create_index('ix_sessions_user', 'packing_sessions', ['user_id'], unique=False)
    op.create_table('packing_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('measurement_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measurement_id'], ['measurements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['packing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_measurement', 'packing_items', ['measurement_id'], unique=False)
    op.create_index('ix_items_session', 'packing_items', ['session_id'], unique=False)
    op.create_table('packing_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('variant_index', sa.Integer(), nullable=False),
    sa.Column('box_l_mm', sa.Float(), nullable=False),
    sa.Column('box_w_mm', sa.Float(), nullable=False),
    sa.Column('box_h_mm', sa.Float(), nullable=False),
    sa.Column('box_volume_cm3', sa.Float(), nullable=False),
    sa.Column('placements_json', sa.Text(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['packing_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_results_selected', 'packing_results', ['session_id', 'selected'], unique=False, postgresql_where='selected = true')
    op.create_index('ix_results_session', 'packing_results', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_results_session', table_name='packing_results')
    op.drop_index('ix_results_selected', table_name='packing_results', postgresql_where='selected = true')
    op.drop_table('packing_results')
    op.drop_index('ix_items_session', table_name='packing_items')
    op.drop_index('ix_items_measurement', table_name='packing_items')
    op.drop_table('packing_items')
    op.drop_index('ix_sessions_user', table_name='packing_sessions')
    op.drop_index('ix_sessions_created', table_name='packing_sessions')
    op.drop_table('packing_sessions')
    op.drop_index('ix_measurements_user', table_name='measurements')
    op.drop_index('ix_measurements_product', table_name='measurements')
    op.drop_index('ix_measurements_measured_at', table_name='measurements')
    op.drop_table('measurements')
    op.drop_index('ix_users_login', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_products_qr', table_name='products', postgresql_where='qr_code IS NOT NULL')
    op.drop_table('products')
    # ### end Alembic commands ###
