"""Add measurement status enum

Revision ID: <auto-generated>
Revises: 953f31aa4b13
Create Date: 2026-05-14

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision = '<auto-generated>'
down_revision = '953f31aa4b13'
branch_labels = None
depends_on = None


def upgrade():
    # Создаём ENUM-тип на уровне БД (PostgreSQL)
    measurement_status_enum = postgresql.ENUM(
        'pending', 'processing', 'done', 'error',
        name='measurement_status_enum',
        create_type=True
    )
    measurement_status_enum.create(op.get_bind(), checkfirst=True)
    
    # Добавляем колонку status с дефолтным значением
    op.add_column(
        'measurements',
        sa.Column(
            'status',
            measurement_status_enum,
            nullable=False,
            server_default='pending'
        )
    )
    
    # Опционально: создаём индекс для ускорения фильтрации по статусу
    op.create_index('ix_measurements_status', 'measurements', ['status'])


def downgrade():
    # Удаляем индекс
    op.drop_index('ix_measurements_status', table_name='measurements')
    
    # Удаляем колонку
    op.drop_column('measurements', 'status')
    
    # Удаляем ENUM-тип (только если он больше нигде не используется)
    measurement_status_enum = postgresql.ENUM(
        'pending', 'processing', 'done', 'error',
        name='measurement_status_enum',
        create_type=False
    )
    measurement_status_enum.drop(op.get_bind(), checkfirst=True)